server:
  port: 6005
spring:
  application:
    name: service-home
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.1:8848 # 配置nacos注册中心地址
  datasource: # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  profiles:
    active: dev # 开发环境配置文件
  redis:
    host: 172.17.0.1
    port: 6379
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com/lc/home/mapper/xml/*.xml
