server:
  port: 6002
spring:
  mail:
    host: 
    username: 
    password: 
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8
  application:
    name: service-ucenter
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.1:8848
  datasource: # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  profiles:
    active: dev # 开发环境配置文件
  redis:
    host: 172.17.0.1
    port: 6379
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com/lc/ucenter/mapper/xml/*.xml
default-setting:
  avatar: 
  passwd: 
  mail:
    subject: "欢迎注册《离散数学》教学网站！" #邮件标题
    count-left: "尊敬的用户您好，您正在注册《离散数学》教学网站，您的验证码为"
    count-right: "！验证码五分钟内有效，请确保是本人操作，不要将验证码泄露给其他人!"
    from: ""
    username: "《离散数学》教学网站"

